<a href="https://colab.research.google.com/github/crshao/tensorflow-python-neural-networks/blob/main/IntroToTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [2]:
#creating tensors
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(29, tf.int16)
floating = tf.Variable(3.23, tf.float64)

In [12]:
#rank/degree = number of dimensions
rank1_tensor = tf.Variable(["Test", "Ok", "Tim"], tf.string)
rank2_tensor = tf.Variable([["test", "asdfss", "haha"], ["asdf", "adf", "sdf"]], tf.string)

print(tf.rank(string))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [13]:
#shape = amount of elements that exists in each extension
rank2_tensor.shape

TensorShape([2, 3])

In [17]:
#changing shape
tensor1 = tf.ones([1, 2, 3]) #tf.ones() creates a shape [1, 2, 3] tensor full of ones
print("tensor1:\n", tensor1)

tensor2 = tf.reshape(tensor1, [2, 3, 1]) #reshape existing data to shape [2, 3, 1]
print("tensor2:\n", tensor2)

tensor3 = tf.reshape(tensor2, [3, -1]) #-1 tells the tensor to calculate the size of the dimension in that place, this will reshape tensor to [3, 2]
print("tensor3:\n", tensor3)

tensor1:
 tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tensor2:
 tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tensor3:
 tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [19]:
#types of tensors
#-Variable
#-Constant
#-Placeholder
#-SparseTensor

# with tf.Session() as sess: #creates a session using the default graph
#   rank1_tensor.eval() #tensor will of course be the name of your tensor

AttributeError: ignored

In [22]:
#DEMO

t = tf.zeros([5, 5, 5, 5])
print(t)

t = tf.reshape(t, [125, -1]) # == t = tf.reshape(t, [625])
print(t)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.